name: f1_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  shimmer_animation: ^2.1.0+1
  dio: ^5.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/sample_track.png
  fonts:
    - family: F1
      fonts:
        - asset: assets/fonts/f1/Formula1-Black.ttf
        - asset: assets/fonts/f1/Formula1-Bold-4.ttf
        - asset: assets/fonts/f1/Formula1-Regular-1.ttf
        - asset: assets/fonts/f1/Formula1-Wide.ttf
