name: f1_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  shimmer_animation: ^2.1.0+1
  dio: ^5.3.3
  cool_dropdown: ^2.1.0
  scrollable_list_tab_scroller: ^1.1.2
  buttons_tabbar: ^1.3.8
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_timer_countdown: ^1.0.6
  flutter_local_notifications: ^16.1.0
  workmanager: ^0.5.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0
  dotted_border: ^2.1.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  image: ^4.1.3
  tflite_flutter: ^0.10.3
  persistent_bottom_nav_bar_v2: ^4.2.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/machine_learning/
    - assets/images/alfaromeo.png
    - assets/images/alphatauri.png
    - assets/images/astonmartin.jpg
    - assets/images/ferrari.png
    - assets/images/haas.png
    - assets/images/mclaren.png
    - assets/images/mercedes.png
    - assets/images/redbull.png
    - assets/images/william.png
    - assets/images/sample_track.png
    - assets/images/

  fonts:
    - family: F1
      fonts:
        - asset: assets/fonts/f1/Formula1-Black.ttf
        - asset: assets/fonts/f1/Formula1-Bold-4.ttf
        - asset: assets/fonts/f1/Formula1-Regular-1.ttf
        - asset: assets/fonts/f1/Formula1-Wide.ttf
